# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run build:clean
  displayName: 'Build the package'
  
- task: CopyFiles@2
  inputs:
        SourceFolder: 'dist'
        TargetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'Copy archives to artifacts staging directory'

- task: CopyFiles@2
  inputs:
    Contents: '**\package.json'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true/
  displayName: 'Copy package json'

- task: CopyFiles@2
  inputs:
    Contents: '**\README.md'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true/
  displayName: 'Copy ReadMe'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'package'
    publishLocation: 'Container'
  displayName: 'Publish artifacts'
